apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-app
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/local/apps
  prune: true
  wait: true
  dependsOn:
    - name: infra
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
